### ISSUE TITLE
Жди докс

### ISSUE THREAD

**Issue by mxTeamCEO** [Error567887/conky-config#1]
переходи на хипрленд

**Comment by Error567887** [comment]
#СтопХайперлендПопулизатион

**Comment by Error567887** [comment]
![Uploading IMG_20240907_203414_595.jpg…]()

**Comment by Error567887** [comment]
![IMG_20240907_203414_595](https://github.com/user-attachments/assets/563f81de-efc8-4933-a6f6-10ba3d729dc2)

**Comment by Error567887** [comment]
> > #СтопХайперлендПопулизатион
> 
> нет, не асилил тайлинги

да поставлю я арч и хупр, ток не насилуй меня

**Comment by Error567887** [comment]
или нет
мне лень

**Comment by mxTeamCEO** [comment]
> или нет мне лень

ща изнасилую

**Comment by Error567887** [comment]
> > или нет мне лень
> 
> ща изнасилую

нет

**Comment by GentOwU** [comment]
> > > или нет мне лень
> > 
> > 
> > ща изнасилую
> 
> нет

да
